#' @export
#'
#' @param dictionary Specify which dictionary you would like to use.
#'   Currently supports "Cholera", "Measles", "Meningitis", "AJS" and "Mortality".
#'
#' @param varnames Specify name of column that contains varnames. Currently
#'   default set to "Item".  (this can probably be deleted once dictionaries
#'   standardise) If `dictionary` is "Mortality", `varnames` needs to be "column_name"`.
#'
#' @param numcases For fake data, specify the number of cases you want (default is 300
#'
#' @rdname msf_dict
gen_data <- function(dictionary, varnames = "data_element_shortname", numcases = 300) {

  # Three datasets:
  # 1) dat_dict = msf data dicationary generated by (msf_dict)
  # 2) dat_output = formatting of data dictionary to make use for sampling
  # 3) dis_output = dictionary dataset generated from sampling (exported)

  # define which ones are outbreaks and which ones are survey datasets
  # get msf dictionary specific data dictionary
  dict <- get_dictionary(dictionary)
  dictionary <- unlist(dict, use.names = FALSE)
  is_survey <- length(dict$survey) == 1

  if (is_survey) {
    dat_dict <- msf_dict_survey(disease = dict$survey, tibble = FALSE, compact = TRUE)
  } else {
    dat_dict <- msf_dict(disease = dict$outbreak, tibble = FALSE, compact = TRUE)
  }

  # # drop extra columns (keep varnames and code options)
  dis_output <- template_data_frame_categories(dat_dict, numcases, varnames, survey = is_survey)

  # Use data dictionary to define which vars are dates
  datevars <- dat_dict[[varnames]][dat_dict$data_element_valuetype == "DATE"]

  # sample between two dates
  posidates <- seq(as.Date("2018-01-01"), as.Date("2018-04-30"), by = "day")

  # fill the date columns with dates
  for (i in datevars) {
    dis_output[[i]] <- sample(posidates, numcases, replace = TRUE)
  }

  if (!is_survey) {

    # Make sure exit dates don't come before entrance dates
    dis_output <- fix_dates(dis_output)

    # Patient identifiers
    dis_output$case_number <- sprintf("A%d", seq(numcases))

    # treatment site facility
    dis_output$treatment_facility_site <- sample(1:50, numcases, replace = TRUE)

    # patient origin (categorical from a dropdown)
    dis_output$patient_origin <- gen_village(numcases)

    # treatment location (categorical from a dropdown)
    dis_output$treatment_location <- gen_ward(numcases)

    # patient origin free text
    dis_output$patient_origin_free_text <- gen_freetext(numcases)
  }

  # GENERATE AGES --------------------------------------------------------------

  dis_output <- gen_ages(dis_output, numcases, set_age_na = dictionary != "Mortality")


  # DISEASE-SPECIFIC GENERATORS ------------------------------------------------
  if (dictionary == "Cholera" | dictionary == "Measles" | dictionary == "AJS") {
    # In this case, not female == not applicable
    dis_output$pregnant[dis_output$sex != "F"] <- "NA"

    # This includes all who are either not female or female and currently
    # pregnant
    NOT_CURRENTLY_PREGNANT <- dis_output$sex != "F" | dis_output$pregnant != "Y"

    dis_output$foetus_alive_at_admission[NOT_CURRENTLY_PREGNANT]  <- NA
    dis_output$trimester[NOT_CURRENTLY_PREGNANT]                  <- NA
    # delivery event is a TRUE only category, meaning that it either is a 1 or
    # NA kind of thing.
    dis_output$delivery_event[NOT_CURRENTLY_PREGNANT] <- "NA"

    NO_DELIVERY <- dis_output$delivery_event != "1"

    dis_output$pregnancy_outcome_at_exit[NOT_CURRENTLY_PREGNANT] <- NA
    dis_output$pregnancy_outcome_at_exit[NO_DELIVERY]            <- NA
  }


  if (dictionary == "Cholera") {
    dis_output$ors_consumed_litres <- sample(1:10, numcases, replace = TRUE)
    dis_output$iv_fluids_received_litres <- sample(1:10, numcases, replace = TRUE)
  }

  if (dictionary == "Measles") {

    dis_output$baby_born_with_complications[NO_DELIVERY] <- NA

    # fix vaccine stuff among non vaccinated
    NOTVACC <- which(!dis_output$previously_vaccinated %in% c("C", "V"))

    dis_output$previous_vaccine_doses_received[NOTVACC] <- NA
    dis_output$date_of_last_vaccination[NOTVACC] <- NA

  }

  if (dictionary == "Meningitis") {
    # T1 lab sample dates before admission
    # add 2 to admission....

    dis_output <- enforce_timing(dis_output,
      first  = "date_of_consultation_admission",
      second = "date_ti_sample_sent",
      2
    )

    # fix pregnancy delivery
    dis_output$delivery_event[dis_output$sex != "F"] <- "NA"

    # fix vaccine stuff among not vaccinated
    NOTVACC <- which(
      !dis_output$vaccinated_meningitis_routine %in% c("C", "V") & 
      !dis_output$vaccinated_meningitis_mvc %in% c("C", "V")
    )

    dis_output$name_meningitis_vaccine[NOTVACC] <- NA
    dis_output$date_of_last_vaccination[NOTVACC] <- NA
  }

  if (dictionary == "Mortality") {


    dis_output <- gen_hh_clusters(dis_output, 
      n = numcases,
      cluster = "cluster_number", 
      household = "q65_iq4"
    )

    # use household num as a standin for fact_0_id for now
    dis_output$fact_0_id <- dis_output$q65_iq4

    # q53_cq4a ("Why is no occupant agreeing to participate?") shoud be NA if
    # Head of Household answers the questions (q49_cq3)
    dis_output$q53_cq4a[dis_output$q49_cq3 == "Yes"] <- factor(NA, levels(dis_output$q53_cq4a))
    # assume person is not born during study when age > 1
    dis_output$q87_q32_born[dis_output$q155_q5_age_year > 1] <- factor("No", levels(dis_output$q87_q32_born))
    dis_output$q88_q33_born_date[dis_output$q155_q5_age_year > 1] <- NA
    # pregnancy set to NA for males
    dis_output$q152_q7_pregnant[dis_output$q4_q6_sex == "Male"] <- NA

    # resample death yes/no to have lower death rates
    dis_output$q136_q34_died <- sample(c("Yes", "No"), nrow(dis_output), prob = c(0.05, 0.95), replace = TRUE)
    # set Columns that are relate to "death" as NA if "q136_q34_died" is "No"
    died <- dis_output$q136_q34_died == "No"
    dis_output[died, c("q137_q35_died_date", "q138_q36_died_cause",
                       "q141_q37_died_violence", "q143_q41_died_place",
                       "q145_q43_died_country")] <- NA
    # pregnancy related cause of death n.a. for too old/young and for males
    no_pregnancy <- dis_output$q138_q36_died_cause == "Pregnancy-related" &
                      (dis_output$q4_q6_sex == "Male"    |
                       dis_output$q155_q5_age_year >= 50 |
                       dis_output$q155_q5_age_year < 12
                      )

    no_pregnancy[is.na(no_pregnancy)] <- FALSE # replace NAs
    dis_output[no_pregnancy, "q138_q36_died_cause"] <- "Unknown"

    # fix arrival/leave dates
    dis_output$q41_q25_hh_arrive_date <-
      pmin(dis_output$q41_q25_hh_arrive_date,
           dis_output$q45_q29_hh_leave_date,
           dis_output$q88_q33_born_date, na.rm = TRUE)

    # leave date
    chn_date <- dis_output$q45_q29_hh_leave_date <= dis_output$q41_q25_hh_arrive_date
    chn_date2 <- dis_output$q45_q29_hh_leave_date < dis_output$q88_q33_born_date
    chn_date[is.na(chn_date)] <- FALSE
    chn_date2[is.na(chn_date2)] <- FALSE

    dis_output$q45_q29_hh_leave_date[chn_date] <- dis_output$q41_q25_hh_arrive_date[chn_date] + sample(5:30, sum(chn_date), replace = TRUE)
    dis_output$q45_q29_hh_leave_date[chn_date2] <- dis_output$q88_q33_born_date[chn_date2] + sample(5:30, sum(chn_date2), replace = TRUE)

    # died date
    chn_date <- dis_output$q137_q35_died_date <= dis_output$q41_q25_hh_arrive_date
    chn_date2 <- dis_output$q137_q35_died_date < dis_output$q88_q33_born_date
    chn_date[is.na(chn_date)] <- FALSE
    chn_date2[is.na(chn_date2)] <- FALSE
    dis_output$q137_q35_died_date[chn_date] <- dis_output$q41_q25_hh_arrive_date[chn_date] + sample(5:30, sum(chn_date), replace = TRUE)
    dis_output$q137_q35_died_date[chn_date2] <- dis_output$q88_q33_born_date[chn_date2] + sample(5:30, sum(chn_date2), replace = TRUE)

    dis_output$q45_q29_hh_leave_date[!is.na(dis_output$q137_q35_died_date)] <- NA

    # more plausibility checks of generated data might be implemented in the future
  }

  if (dictionary == "Nutrition") {

    dis_output <- gen_hh_clusters(dis_output, 
      n = numcases,
      cluster = "cluster_number", 
      household = "household_id"
    )

    # use household num as a standin for fact_0_id for now
    dis_output$fact_0_id <- dis_output$household_id


    # age in months (1 to 60 - i.e. under 5 years)
    dis_output$age_month <- sample(1:60L, numcases, replace = TRUE)

    # height in cm
    dis_output$height <- round(
      runif(numcases, 40, 120),
      digits = 1
    )

    # weight in kg
    dis_output$weight <- round(
      runif(numcases, 2, 30),
      digits = 1
    )

    # MUAC in mm
    dis_output$muac_mm_left_arm <- sample(80:190, numcases, replace = TRUE)
  }

  if (dictionary == "Vaccination") {


    dis_output <- gen_hh_clusters(dis_output, 
      n = numcases,
      cluster = "q77_what_is_the_cluster_number", 
      household = "q14_hh_no"
    )
    

    dis_output <- gen_eligible_interviewed(dis_output,
      household = "q14_hh_no",
      cluster = "q77_what_is_the_cluster_number"
    )

    # use household num as a standin for fact_0_id for now
    dis_output$fact_0_id <- dis_output$q14_hh_no


    # age in yr (0 to 14) - assuming doing vaccination coverage among those aged less than 15 yrs
    dis_output$q10_age_yr <- sample(0:14L, numcases, replace = TRUE)

    # age in mth (0 to 11)
    dis_output$q55_age_mth[dis_output$q10_age_yr < 1] <- sample(0:11L,
                                                                nrow(dis_output[dis_output$q10_age_yr < 1,]),
                                                                replace = TRUE)

  }


  # return dataset as a tibble
  dplyr::as_tibble(dis_output)

}





