#' @noRd
#'
#' @param dictionary Specify which dictionary you would like to use.
#'   Currently supports "Cholera",
#'   To be added: "Measles", "Lassa" and "Yellow fever".
#'
#' @param varnames Specify name of column that contains varnames. Currently
#'   default set to "Item".  (this can probably be deleted once dictionaries
#'   standardise) If `dictionary` is "Mortality", `varnames` needs to be "column_name"`.
#'
#' @param numcases For fake data, specify the number of cases you want (default is 300)
#'
#' @keywords internal
gen_who_data <- function(dictionary, dat_dict, is_survey, varnames = "data_element_shortname", numcases = 300) {

  # Three datasets:
  # 1) dat_dict = who data dicationary generated by (who_dict)
  # 2) dat_output = formatting of data dictionary to make use for sampling
  # 3) dis_output = dictionary dataset generated from sampling (exported)

  # # drop extra columns (keep varnames and code options)
  dis_output <- template_data_frame_categories(dat_dict, numcases, varnames, survey = is_survey)

  # Use data dictionary to define which vars are dates
  datevars <- dat_dict[[varnames]][dat_dict$data_element_valuetype == "DATE"]

  # sample between two dates
  posidates <- seq(as.Date("2018-01-01"), as.Date("2018-04-30"), by = "day")

}

