#' @noRd
#'
#' @param dictionary Specify which dictionary you would like to use.
#'   Currently supports "Cholera", "Measles", "Meningitis", "AJS" and "Mortality".
#'
#' @param varnames Specify name of column that contains varnames. Currently
#'   default set to "data_element_shortname".  (this can probably be deleted once dictionaries
#'   standardise) If `dictionary` is in surveys then `varnames` needs to be "column_name"`.
#'
#' @param numcases For fake data, specify the number of cases you want (default is 300)
#'
#' @keywords internal
gen_msf_data <- function(dictionary, dat_dict, is_survey, varnames = "data_element_shortname", numcases = 300) {

  # Three datasets:
  # 1) dat_dict = msf data dicationary generated by (msf_dict)
  # 2) dat_output = formatting of data dictionary to make use for sampling
  # 3) dis_output = dictionary dataset generated from sampling (exported)

  # # drop extra columns (keep varnames and code options)
  dis_output <- template_data_frame_categories(dat_dict, numcases, varnames, survey = is_survey)

  # Use data dictionary to define which vars are dates
  datevars <- dat_dict[[varnames]][dat_dict$data_element_valuetype == "DATE"]

  # sample between two dates
  posidates <- seq(as.Date("2018-01-01"), as.Date("2018-04-30"), by = "day")

  # fill the date columns with dates
  for (i in datevars) {
    dis_output[[i]] <- sample(posidates, numcases, replace = TRUE)
  }

  if (!is_survey) {

    # Make sure exit dates don't come before entrance dates
    dis_output <- fix_dates(dis_output)

    # Patient identifiers
    dis_output$case_number <- sprintf("A%d", seq(numcases))

    # treatment site facility
    dis_output$treatment_facility_site <- sample(1:50, numcases, replace = TRUE)

    # patient origin (categorical from a dropdown)
    dis_output$patient_origin <- gen_village(numcases)

    # treatment location (categorical from a dropdown)
    dis_output$treatment_location <- gen_ward(numcases)

    # patient origin free text
    dis_output$patient_origin_free_text <- gen_freetext(numcases)
  }

  # GENERATE AGES --------------------------------------------------------------

  dis_output <- gen_ages(dis_output, numcases, set_age_na = dictionary != "Mortality")


  # DISEASE-SPECIFIC GENERATORS ------------------------------------------------
  if (dictionary == "Cholera" | dictionary == "Measles" | dictionary == "AJS") {
    # In this case, not female == not applicable
    dis_output$pregnant[dis_output$sex != "F"] <- "NA"

    # This includes all who are either not female or female and currently
    # pregnant
    NOT_CURRENTLY_PREGNANT <- dis_output$sex != "F" | dis_output$pregnant != "Y"

    dis_output$foetus_alive_at_admission[NOT_CURRENTLY_PREGNANT] <- NA
    dis_output$trimester[NOT_CURRENTLY_PREGNANT] <- NA
    # delivery event is a TRUE only category, meaning that it either is a 1 or
    # NA kind of thing.
    dis_output$delivery_event[NOT_CURRENTLY_PREGNANT] <- "NA"

    NO_DELIVERY <- dis_output$delivery_event != "1"

    dis_output$pregnancy_outcome_at_exit[NOT_CURRENTLY_PREGNANT] <- NA
    dis_output$pregnancy_outcome_at_exit[NO_DELIVERY] <- NA
  }


  if (dictionary == "Cholera") {
    dis_output$ors_consumed_litres <- sample(1:10, numcases, replace = TRUE)
    dis_output$iv_fluids_received_litres <- sample(1:10, numcases, replace = TRUE)
  }

  if (dictionary == "Measles") {
    dis_output$baby_born_with_complications[NO_DELIVERY] <- NA

    # fix vaccine stuff among non vaccinated
    NOTVACC <- which(!dis_output$previously_vaccinated %in% c("C", "V"))

    dis_output$previous_vaccine_doses_received[NOTVACC] <- NA
    dis_output$date_of_last_vaccination[NOTVACC] <- NA
  }

  if (dictionary == "Meningitis") {
    # T1 lab sample dates before admission
    # add 2 to admission....
    dis_output <- enforce_timing(dis_output,
      first  = "date_of_consultation_admission",
      second = "date_ti_sample_sent",
      2
    )

    # fix pregnancy delivery
    dis_output$delivery_event[dis_output$sex != "F"] <- "NA"

    # fix vaccine stuff among not vaccinated
    NOTVACC <- which(
      !dis_output$vaccinated_meningitis_routine %in% c("C", "V") &
        !dis_output$vaccinated_meningitis_mvc %in% c("C", "V")
    )

    dis_output$name_meningitis_vaccine[NOTVACC] <- NA
    dis_output$date_of_last_vaccination[NOTVACC] <- NA
  }

  if (dictionary == "Mortality") {
    dis_output <- gen_hh_clusters(dis_output,
      n = numcases,
      cluster = "cluster_number",
      household = "q65_iq4"
    )

    # use household num as a standin for fact_0_id for now
    dis_output$fact_0_id <- dis_output$q65_iq4

    # q53_cq4a ("Why is no occupant agreeing to participate?") shoud be NA if
    # Head of Household answers the questions (q49_cq3)
    dis_output$q53_cq4a[dis_output$q49_cq3 == "Yes"] <- NA

    # assume person is not born during study when age > 1
    OVER_ONE <- dis_output$q155_q5_age_year > 1
    dis_output$q87_q32_born[OVER_ONE] <- factor("No", levels(dis_output$q87_q32_born))
    dis_output$q88_q33_born_date[OVER_ONE] <- NA

    # pregnancy set to NA for males
    dis_output$q152_q7_pregnant[dis_output$q4_q6_sex == "Male"] <- NA

    # resample death yes/no to have lower death rates
    dis_output$q136_q34_died <- sample(c("Yes", "No"),
      size = nrow(dis_output),
      prob = c(0.05, 0.95),
      replace = TRUE
    )

    # set columns that are relate to "death" as NA if "q136_q34_died" is "No"
    died <- dis_output$q136_q34_died == "No"
    dcols <- c(
      "q137_q35_died_date",
      "q138_q36_died_cause",
      "q141_q37_died_violence",
      "q143_q41_died_place",
      "q145_q43_died_country"
    )
    for (d in dcols) {
      dis_output[[d]][died] <- NA
    }

    # pregnancy related cause of death n.a. for too old/young and for males
    pregnancy_not_possible <- with(
      dis_output,
      q4_q6_sex == "Male" | q155_q5_age_year >= 50 | q155_q5_age_year < 12
    )

    no_pregnancy <- dis_output$q138_q36_died_cause == "Pregnancy-related" & pregnancy_not_possible

    no_pregnancy[is.na(no_pregnancy)] <- FALSE # replace NAs
    dis_output[["q138_q36_died_cause"]][no_pregnancy] <- "Unknown"

    # fix arrival/leave dates
    dis_output$q41_q25_hh_arrive_date <- with(
      dis_output,
      pmin(
        q41_q25_hh_arrive_date,
        q45_q29_hh_leave_date,
        q88_q33_born_date,
        na.rm = TRUE
      )
    )

    # leave date
    dis_output <- enforce_timing(dis_output,
      first  = "q41_q25_hh_arrive_date",
      second = "q45_q29_hh_leave_date",
      5:30
    )
    dis_output <- enforce_timing(dis_output,
      first  = "q88_q33_born_date",
      second = "q45_q29_hh_leave_date",
      5:30,
      inclusive = TRUE
    )

    # died date
    dis_output <- enforce_timing(dis_output,
      first  = "q41_q25_hh_arrive_date",
      second = "q137_q35_died_date",
      5:30
    )
    dis_output <- enforce_timing(dis_output,
      first  = "q88_q33_born_date",
      second = "q137_q35_died_date",
      5:30,
      inclusive = TRUE
    )

    dis_output$q45_q29_hh_leave_date[!is.na(dis_output$q137_q35_died_date)] <- NA

    # more plausibility checks of generated data might be implemented in the future
  }

  if (dictionary == "Nutrition") {
    dis_output <- gen_hh_clusters(dis_output,
      n = numcases,
      cluster = "cluster_number",
      household = "household_id"
    )

    # use household num as a standin for fact_0_id for now
    dis_output$fact_0_id <- dis_output$household_id


    # age in months (1 to 60 - i.e. under 5 years)
    dis_output$age_month <- sample(1:60L, numcases, replace = TRUE)

    # height in cm
    dis_output$height <- round(
      runif(numcases, 40, 120),
      digits = 1
    )

    # weight in kg
    dis_output$weight <- round(
      runif(numcases, 2, 30),
      digits = 1
    )

    # MUAC in mm
    dis_output$muac_mm_left_arm <- sample(80:190, numcases, replace = TRUE)
  }

  if (dictionary == "Vaccination") {
    dis_output <- gen_hh_clusters(dis_output,
      n = numcases,
      cluster = "q77_what_is_the_cluster_number",
      household = "q14_hh_no"
    )

    # use household num as a standin for fact_0_id for now
    dis_output$fact_0_id <- dis_output$q14_hh_no


    # age in yr (0 to 14) - assuming doing vaccination coverage among those aged less than 15 yrs
    dis_output$q10_age_yr <- sample_age(14L, numcases)

    # age in mth (0 to 11)
    zero_yrs <- dis_output$q10_age_yr < 1
    dis_output$q55_age_mth[zero_yrs] <- sample_age(11L, sum(zero_yrs))
  }


  # return dataset as a tibble
  dplyr::as_tibble(dis_output)
}
